package com.geek.rpg.game.factory.templates;


import com.geek.rpg.game.factory.JsonLoader;
import com.geek.rpg.game.factory.JsonTemplate;

public class AnimationTemplate extends JsonTemplate
{
	public static final JsonLoader<AnimationTemplate> jsonLoader = new JsonLoader<AnimationTemplate>("animations", AnimationTemplate[].class);

	//generated by jsonLoader
	private String textureName = "noTexture.png";
	private float duration = 86400.0f;
	private int frames = 1;

	public String getTextureName()
	{
		return textureName;
	}

	public float getDuration()
	{
		return duration;
	}

	public int getFrames()
	{
		return frames;
	}
}
